In [27]:
import tensorflow as tf

from tensorflow.keras.layers import GlobalMaxPooling2D

from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.vgg16 import preprocess_input

if tf.test.gpu_device_name():
      print(f'Default GPU Device: {tf.test.gpu_device_name()}')

model = VGG16(weights='imagenet', include_top=False, input_shape = (224,224,3))
model.trainable = False

from tqdm import tqdm

Default GPU Device: /device:GPU:0


## Building a simple Sequential model

In [2]:
model_seq = tf.keras.Sequential([
      model,
      GlobalMaxPooling2D() #Our top layer
])

Loading an image:

In [3]:
img = image.load_img('0118458003.jpg', target_size=(224,224))

Explicitly convert our image to a numpy array

In [4]:
img_array = image.img_to_array(img)

In [ ]:
img_array.shape

Now, we need to reshape our image since Keras works on a batch instead of a single file.

In [6]:
import numpy as np

expanded_img_array = np.expand_dims(img_array, axis=0)
expanded_img_array.shape

(1, 224, 224, 3)

In [7]:
expanded_img_array

array([[[[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        ...,

        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[255., 255., 255.],
       

Now we need to preprocee the input so that the input of our model is in the correct format where we the images are first converted from RGB to BGR, then each color channel is zero-centered with respect to the ImageNet dataset without scaling.

In [8]:
preprocessed_img = preprocess_input(expanded_img_array)

print(preprocessed_img.shape)
preprocessed_img


(1, 224, 224, 3)


array([[[[151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         ...,
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ]],

        [[151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         ...,
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ]],

        [[151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         ...,
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ]],

        ...,

        [[151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         ...,


Now our input is ready for the model to use to make predictions!

In [10]:
predicted_output = model_seq.predict(preprocessed_img)

1/1 [==============================] - 0s 24ms/step


In [11]:
predicted_output.shape

(1, 512)

We now have a 2D array output but we need a 1D output which we can do using `flatten()`

In [13]:
one_dim_output = predicted_output.flatten()

In [14]:
one_dim_output.shape

(512,)

Now we need to normalize our output:

In [15]:
from numpy.linalg import norm

one_dim_output/norm(one_dim_output)

array([7.9536587e-03, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       1.6879868e-02, 0.0000000e+00, 5.4270964e-02, 6.0746544e-03,
       0.0000000e+00, 2.6220165e-03, 7.5816740e-03, 0.0000000e+00,
       4.1919671e-02, 0.0000000e+00, 0.0000000e+00, 1.1410431e-01,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 7.3987715e-02,
       0.0000000e+00, 0.0000000e+00, 1.2541351e-01, 4.7187757e-02,
       0.0000000e+00, 1.2818965e-02, 0.0000000e+00, 5.3625815e-02,
       4.5631450e-02, 3.7270967e-02, 0.0000000e+00, 0.0000000e+00,
       7.4555323e-02, 8.2960697e-03, 5.2476831e-04, 6.0939204e-02,
       0.0000000e+00, 7.4266396e-02, 4.2722798e-03, 9.8760398e-03,
       2.6193440e-02, 9.9947699e-04, 3.4360256e-02, 7.8608049e-03,
       6.0683720e-02, 8.2416013e-02, 4.3508690e-02, 9.4479822e-02,
       0.0000000e+00, 0.0000000e+00, 2.7049888e-02, 1.5468253e-02,
       9.3892522e-02, 0.0000000e+00, 3.4567833e-02, 2.9050058e-03,
       2.6759494e-02, 0.0000000e+00, 8.7739580e-04, 2.4744840e

In [29]:
def extract_features(img_path, model):
    img_file = image.load_img(img_path, target_size=(224,224))
    img_array = image.img_to_array(img_file)
    expanded_img_array = np.expand_dims(img_array, axis=0)
    preprocessed_img = preprocess_input(expanded_img_array)
    predicted_output = model.predict(preprocessed_img)
    one_dim_output = predicted_output.flatten()
    output = one_dim_output/norm(one_dim_output)

    return output

In [33]:
import os
import random
import shutil

# Path to the source folder
src_folder = '..\\Processed_Images'

# Path to the destination folder
dst_folder = '..\\New_test'

# Get a list of all image files in the source folder
img_files = [f for f in os.listdir(src_folder) if f.endswith('.jpg')]

# Choose 1000 random images from the list
selected_imgs = random.sample(img_files, 1000)

# Move the selected images to the destination folder
for img in selected_imgs:
    src_path = os.path.join(src_folder, img)
    dst_path = os.path.join(dst_folder, img)
    shutil.move(src_path, dst_path)


In [21]:
filenames = []
img_names = []

for file in os.listdir('..\\Test_all'):
    img_names.append(file[1:])
    filenames.append(os.path.join('..\\Test_all', file))

filenames
img_names

['112679048.jpg',
 '190021001.jpg',
 '190021003.jpg',
 '291333021.jpg',
 '293244002.jpg',
 '304766008.jpg',
 '308154008.jpg',
 '309434006.jpg',
 '315509001.jpg',
 '318035022.jpg',
 '351484027.jpg',
 '352811033.jpg',
 '367372001.jpg',
 '377266018.jpg',
 '392168001.jpg',
 '395127028.jpg',
 '426019008.jpg',
 '438147002.jpg',
 '442915017.jpg',
 '443696015.jpg',
 '445901004.jpg',
 '449570054.jpg',
 '449897048.jpg',
 '451744015.jpg',
 '456032019.jpg',
 '459756009.jpg',
 '463117006.jpg',
 '468591018.jpg',
 '477904002.jpg',
 '477970001.jpg',
 '478022001.jpg',
 '483290003.jpg',
 '485542004.jpg',
 '485552001.jpg',
 '485552008.jpg',
 '487050029.jpg',
 '487051002.jpg',
 '487937004.jpg',
 '488320001.jpg',
 '488546008.jpg',
 '488561015.jpg',
 '491036012.jpg',
 '493814021.jpg',
 '494910002.jpg',
 '496632001.jpg',
 '497284017.jpg',
 '498739002.jpg',
 '500814001.jpg',
 '501119009.jpg',
 '501619006.jpg',
 '501619023.jpg',
 '501722004.jpg',
 '504890002.jpg',
 '505083003.jpg',
 '506369003.jpg',
 '50732000

In [ ]:
feature_list = []

for file in tqdm(filenames):
    feature_list.append(extract_features(file, model_seq))

print(np.array(feature_list).shape)

In [31]:
print(np.array(feature_list).shape)

(1000, 512)


In [32]:
import pickle

pickle.dump(feature_list, open('embeddings.pkl', 'wb'))

pickle.dump(img_names, open('file_names.pkl', 'wb'))

In [2]:
import os
img_paths = []

for file in os.listdir('..\\Test_all'):
    img_paths.append(file)

img_paths

['0112679048.jpg',
 '0190021001.jpg',
 '0190021003.jpg',
 '0291333021.jpg',
 '0293244002.jpg',
 '0304766008.jpg',
 '0308154008.jpg',
 '0309434006.jpg',
 '0315509001.jpg',
 '0318035022.jpg',
 '0351484027.jpg',
 '0352811033.jpg',
 '0367372001.jpg',
 '0377266018.jpg',
 '0392168001.jpg',
 '0395127028.jpg',
 '0426019008.jpg',
 '0438147002.jpg',
 '0442915017.jpg',
 '0443696015.jpg',
 '0445901004.jpg',
 '0449570054.jpg',
 '0449897048.jpg',
 '0451744015.jpg',
 '0456032019.jpg',
 '0459756009.jpg',
 '0463117006.jpg',
 '0468591018.jpg',
 '0477904002.jpg',
 '0477970001.jpg',
 '0478022001.jpg',
 '0483290003.jpg',
 '0485542004.jpg',
 '0485552001.jpg',
 '0485552008.jpg',
 '0487050029.jpg',
 '0487051002.jpg',
 '0487937004.jpg',
 '0488320001.jpg',
 '0488546008.jpg',
 '0488561015.jpg',
 '0491036012.jpg',
 '0493814021.jpg',
 '0494910002.jpg',
 '0496632001.jpg',
 '0497284017.jpg',
 '0498739002.jpg',
 '0500814001.jpg',
 '0501119009.jpg',
 '0501619006.jpg',
 '0501619023.jpg',
 '0501722004.jpg',
 '0504890002

In [4]:
import pickle
pickle.dump(img_paths, open('file_names_full.pkl', 'wb'))